### ISSUE TITLE
Translations and a constant issue with 0.109.0, causing component to fail setup and not load

### ISSUE THREAD

**Issue by rccoleman** [shbatm/hacs-isy994#52]
I'm getting the following in home-assistant.log after updating to 0.109.0:

```
2020-04-29 10:17:40 ERROR (MainThread) [homeassistant.setup] Setup failed for isy994: Unable to import component: cannot import name 'UNIT_UV_INDEX' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

```
2020-04-29 10:18:03 WARNING (MainThread) [homeassistant.helpers.translation] isy994: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this
```

For the first one, I removed the two references to "UNIT_UV_INDEX" from const.py and the component is loading and working now.

**Comment by bkvargyas** [comment]
So I can confirm by deleting the two lines that reference UNIT_UV_INDEX in const.py and then renaming the .translation directory to be just "translation" and restarting worked.   I also had to reboot my ISY99i for some reason as well.

**Comment by shbatm** [comment]
Looks like there's about 5 PRs from Home Assistant Core I need to pull in which should fix these for 0.109. I'll get to them in the next several days.

**Comment by rccoleman** [comment]
Awesome, thanks!  I needed my lights to turn on and had to take matters into my own hands for now :)

**Comment by xstrex** [comment]
Yea, I can't wait a few days for my lights and thermostat to fix themselves. Can we get some instructions on how to manually fix it, until a more permanent solution is in place?

**Comment by rccoleman** [comment]
I opened config/custom_components/isy994/const.py in an editor (I used vi through ssh), searched for "UNIT_UV_INDEX" and deleted the lines where it appeared.  As I recall, one was in the import list at the top and the second was in the "UOM_FRIENDLY_NAME" section.

**Comment by xstrex** [comment]
Alright.. 
in this directory: /config/custom_components/isy994/
1. Search the file const.py for "UV", should be lines 45 & 271. Remove both lines
1. Rename ".translations" to "translations" (removing the . )
1. Restart Home Assistant

In some cases, you'll also need to restart your isy994.

**Comment by shbatm** [comment]
Pushed [1.3.7](https://github.com/shbatm/hacs-isy994/releases/tag/v1.3.7) which should fix this. It's still marked as a Beta release for the moment (so make sure to enable "Show Betas" in HACS). As soon as I get a chance to fully test I'll mark it as a full release.
